### ISSUE TITLE
[BUG]: Robotpy sync command throws an exception of wpilib directory non-existent

### ISSUE THREAD

**Issue by lospugs** [robotpy/robotpy-installer#115]
### Problem description

When running py -3 -m robotpy sync on a Windows laptop there was an exception raised for a missing roboty .json file. 

The file was being searched for in
c:\users\<user>\wpilib\2024\robotpy

If WPILib installer is run for all users, or the directory is specified to be something else that path doesn't exist.
On our system that had the bug, WPILib was in \users\Public\wpilib\2024

I manually created the directory:
```mkdir -p \users\Public\wpilib\2024\robotpy``` 

and re-ran the sync command and everything installed successfully.

### Operating System

Windows

### Installed Python Packages

```text
robotpy 2024.2.1.2
robotpy-installer 2024.2.1
```

### Reproducible example code

```text
py -3 -m robotpy sync on a Windows system
```

**Comment by virtuald** [comment]
What's the stack trace?
