### ISSUE TITLE
Smarter roborio connection

### ISSUE THREAD

**Issue by virtuald** [robotpy/robotpy-installer#19]
Should try the USB IP by default and see if that works.

**Comment by auscompgeek** [comment]
If we're going to implement a round-robin sort of thing, I think the best way to do this is to allow users to specify a team number, then we can try mDNS, the USB IP, and 10.TE.AM.2 in order.

**Comment by virtuald** [comment]
Probably affects a user at https://www.chiefdelphi.com/t/robotpy-installation-error-cannot-connect-to-robot-via-ssh/341641
