### ISSUE TITLE
Replace pip.main() in installer

### ISSUE THREAD

**Issue by paigevegna** [robotpy/robotpy-installer#20]
The installer script uses the older version of the `pip` package. Specifically, the code uses the `pip.main()` function, which has been removed since pip version 10.

A quick workaround would be [the callable-pip package](https://pypi.org/project/callable-pip/), a wrapper around pip that allows you to use the `pip.main()` syntax that's currently there. The long-term solution would be to either using `subprocess` to call pip or using import statements.

**Comment by auscompgeek** [comment]
Huh, I could've sworn we fixed this.

**Comment by virtuald** [comment]
Ah yes, duplicate of #15 . @paigevegna if you upgrade your version of the installer it should work for you!
