### ISSUE TITLE
download-pip refuses to download pure-Python wheels

### ISSUE THREAD

**Issue by auscompgeek** [robotpy/robotpy-installer#24]
Noticed this when downloading wpilib-controller.

**Comment by auscompgeek** [comment]
Apparently attempting to install flit on a roboRIO OOMs? (I'm not too sure, getting this second-hand from my team.) So this isn't a great situation.

**Comment by virtuald** [comment]
Interestingly, when I `download-pip flit`, it tries to install the build dependencies locally. /shrugs

**Comment by virtuald** [comment]
Interesting problem, you can't download binary and non-binary dependencies together if you specify platform/implementation/etc.

**Comment by virtuald** [comment]
Fixed in latest installer
