### ISSUE TITLE
pip3 issues

### ISSUE THREAD

**Issue by virtuald** [robotpy/robotpy-installer#3]
* pip 9.x downloads wheels instead of tar.gz of pure python packages, which can be a problem if the wrong python is being used. There's a platform flag you can give to pip 9
* Need to disable pip's caching, we don't need it for this

> Migrated from https://github.com/robotpy/robotpy-wpilib/issues/249

**Comment by auscompgeek** [comment]
> There's a platform flag you can give to pip 9

Would `--implementation py` be enough instead?
