### ISSUE TITLE
Didn’t support for VMX-pi?

### ISSUE THREAD

**Issue by iqv29** [robotpy/robotpy-installer#53]
Didn’t support for VMX-pi?
I'm tried to running robotpy-installer for VMX-pi,but it's not work!

**Comment by virtuald** [comment]
robotpy-installer is only designed to work on the roborio. We do publish raspbian wheels at https://www.tortall.net/~robotpy/wheels/2021/raspbian/ , so you might be able to install those if it's running raspbian. However, you'd need to do it manually.
