### ISSUE TITLE
Detect SSL errors and suggest certifi upgrade

### ISSUE THREAD

**Issue by virtuald** [robotpy/robotpy-installer#57]
Reference: https://www.chiefdelphi.com/t/robotpy-module-not-found/399156/2

I'm guessing that's their problem, as I believe pip uses certifi for certificates instead of the system store.

**Comment by virtuald** [comment]
Well, maybe not. Another thing we could do is add an option to use certifi, it seems that python gives you the option to do that.

**Comment by virtuald** [comment]
Turns out if you browse to the url using MS edge the error goes away. Maybe we just tell the user to do this? We already have a special check of this sort for OSX.

**Comment by TheTripleV** [comment]
Should it just automatically try certifi if the original version fails on that specific error?

**Comment by virtuald** [comment]
That seems reasonable.

**Comment by virtuald** [comment]
I think we do this now.
